echo Lowercasing...
sed y/ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖ/abcdefghijklmnopqrstuvwxyzäö/ ./verbstostem5345.txt.out > ./verbstostem5345.txt.out2
echo Uniqing...
uniq ./verbstostem5345.txt.out2 > ./verbstostem5345.txt.out3
